//! `include_program!` (RFC 0002 §6.1): embed a `.dsrs` artifact at build time.
//!
//! See [`expand`] and the macro's rustdoc in `lib.rs` for the layering
//! contract. The short version: **syntax** is validated here at macro
//! expansion (via [`dsrs_syntax::check`], the shared structural grammar over
//! the same lexer `Program::from_dsrs` uses); **semantics** are validated by
//! the full parser at first use of the emitted `LazyLock`, and forced at CI
//! time by an emitted `#[cfg(test)]` test — the sqlx-offline analogue.

use std::path::{Path, PathBuf};

use proc_macro2::Span;
use quote::{format_ident, quote};

use crate::runtime_path::resolve_dspy_rs_path;

/// Parsed macro input: a single string-literal path.
pub(crate) struct Input {
    pub lit: syn::LitStr,
}

impl syn::parse::Parse for Input {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        let lit: syn::LitStr = input.parse().map_err(|_| {
            syn::Error::new(
                input.span(),
                "expected a string literal path to a `.dsrs` file, e.g. \
                 include_program!(\"programs/qa.dsrs\")",
            )
        })?;
        if !input.is_empty() {
            return Err(syn::Error::new(
                input.span(),
                "include_program! takes exactly one argument: a `.dsrs` path",
            ));
        }
        Ok(Self { lit })
    }
}

/// Resolves `rel` against the candidate base directories, in order:
/// `CARGO_MANIFEST_DIR` (the `include_str!`-adjacent, sqlx-style rule), then
/// the directory of the invoking source file when the compiler exposes it
/// (`--Z`-free since Rust 1.88). Absolute paths are used as-is.
fn resolve(rel: &Path, source_dir: Option<&Path>) -> Result<PathBuf, String> {
    if rel.is_absolute() {
        return Ok(rel.to_path_buf());
    }
    let manifest_dir = std::env::var_os("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .ok_or_else(|| "CARGO_MANIFEST_DIR is not set".to_string())?;
    let primary = manifest_dir.join(rel);
    if primary.exists() {
        return Ok(primary);
    }
    if let Some(dir) = source_dir {
        let fallback = dir.join(rel);
        if fallback.exists() {
            return Ok(fallback);
        }
    }
    // Report the primary attempt: it is the documented resolution rule.
    let err = match std::fs::read(&primary) {
        Err(e) => e.to_string(),
        Ok(_) => "file appeared mid-expansion".to_string(),
    };
    Err(format!(
        "could not read `{}` (tried relative to CARGO_MANIFEST_DIR and the \
         invoking file): {err}",
        rel.display()
    ))
}

/// The macro body. `source_dir` is the invoking file's directory when known
/// (used only as a fallback resolution base; `None` in unit tests).
pub(crate) fn expand(
    input: Input,
    source_dir: Option<PathBuf>,
) -> Result<proc_macro2::TokenStream, syn::Error> {
    let lit = input.lit;
    let rel = lit.value();
    let err_at = |message: String| syn::Error::new(lit.span(), message);

    let full = resolve(Path::new(&rel), source_dir.as_deref())
        .map_err(|e| err_at(format!("include_program!: {e}")))?;

    let bytes = std::fs::read(&full)
        .map_err(|e| err_at(format!("include_program!: could not read `{rel}`: {e}")))?;
    let text = String::from_utf8(bytes).map_err(|_| {
        err_at(format!(
            "include_program!(\"{rel}\"): not a UTF-8 text artifact (`.dsrs` files are text-only)"
        ))
    })?;

    // Build-time gate: syntax only, through the shared dsrs-syntax grammar.
    // Semantic validation happens through the full parser in the emitted
    // runtime/test code below.
    dsrs_syntax::check(&text).map_err(|e| {
        err_at(format!(
            "include_program!(\"{rel}\"): line {}, column {}: {}",
            e.line, e.col, e.message
        ))
    })?;

    // Module name: the file stem, `-` mapped to `_`.
    let stem = full
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| err_at(format!("include_program!(\"{rel}\"): no file stem")))?;
    let mod_name = stem.replace('-', "_");
    let mod_ident: syn::Ident = syn::parse_str(&mod_name).map_err(|_| {
        err_at(format!(
            "include_program!(\"{rel}\"): file stem `{stem}` is not a valid module name \
             (after `-` → `_`); rename the file or wrap the macro in your own module"
        ))
    })?;
    let mod_ident = format_ident!("{}", mod_ident, span = Span::call_site());

    let abs = full.to_str().ok_or_else(|| {
        err_at(format!(
            "include_program!(\"{rel}\"): path is not valid UTF-8"
        ))
    })?;

    let krate = resolve_dspy_rs_path()?;
    let mod_docs = format!(
        "Program module generated by `include_program!(\"{rel}\")`.\n\n\
         The `.dsrs` text is embedded via `include_str!` (rustc re-expands on \
         file change). Build time validated **syntax only**; full parse + \
         validation (`Program::from_dsrs`) runs at first access and in the \
         generated `#[cfg(test)]` test."
    );

    Ok(quote! {
        #[doc = #mod_docs]
        pub mod #mod_ident {
            /// The embedded `.dsrs` source text, byte-for-byte. The
            /// `include_str!` makes rustc track the artifact for rebuilds
            /// (the sqlx trick).
            pub const SOURCE: &str = ::core::include_str!(#abs);

            #[doc(hidden)]
            static __PROGRAM: ::std::sync::LazyLock<
                ::std::result::Result<#krate::ir::Program, #krate::ir::ParseError>,
            > = ::std::sync::LazyLock::new(|| #krate::ir::Program::from_dsrs(SOURCE));

            /// The embedded program, fully parsed and validated on first
            /// access (validation results are cached).
            ///
            /// # Panics
            ///
            /// If the artifact fails full parse/validation — errors the
            /// build-time syntax gate cannot see (types, dataflow, caps).
            /// Run `cargo test` to catch those at CI time via the generated
            /// validation test; use [`try_program`] to handle them at runtime.
            pub fn program() -> &'static #krate::ir::Program {
                match ::std::sync::LazyLock::force(&__PROGRAM) {
                    ::std::result::Result::Ok(p) => p,
                    ::std::result::Result::Err(e) => ::std::panic!(
                        "include_program!({path:?}): embedded program failed full parse/validation: {err}",
                        path = #rel,
                        err = e,
                    ),
                }
            }

            /// Non-panicking accessor for the embedded program.
            pub fn try_program() -> ::std::result::Result<
                &'static #krate::ir::Program,
                &'static #krate::ir::ParseError,
            > {
                ::std::sync::LazyLock::force(&__PROGRAM).as_ref()
            }

            /// Generated by `include_program!`: forces full parse+validation
            /// under `cargo test`, so semantic artifact errors fail CI even
            /// if the program is never accessed at test time (the
            /// sqlx-offline analogue for `.dsrs`).
            #[cfg(test)]
            mod __include_program_validation {
                #[test]
                fn embedded_dsrs_program_validates() {
                    if let ::std::result::Result::Err(e) = super::try_program() {
                        ::std::panic!(
                            "include_program!({path:?}): embedded program failed full parse/validation: {err}",
                            path = #rel,
                            err = e,
                        );
                    }
                }
            }
        }
    })
}
