//! How trainset rows connect to modules.
//!
//! A trainset row is any struct you like — it can carry fields the module never
//! sees (gold labels, metadata, metric-only context like supporting facts). The
//! evaluation loop and optimizers only need one thing from a row: the module's
//! input. [`ToInput`] is that projection. [`ToOutput`] is its counterpart for
//! seeding labeled demos from gold data.
//!
//! Three ways to get an impl:
//!
//! 1. **`#[derive(Example)]`** — mark input fields with `#[input]`, name the
//!    target signature(s) with `#[example(QA)]`; conversions are generated by
//!    field name at compile time.
//! 2. **A `(input, output)` tuple** — `(S::Input, S::Output)` pairs implement
//!    both traits out of the box.
//! 3. **A hand-written impl** — for rows whose field names don't line up.

/// Projects a trainset row into a module's input type.
///
/// Implemented by `#[derive(Example)]`, by `(I, O)` tuples, and by any type
/// for itself (an input-only trainset is just `Vec<S::Input>`).
pub trait ToInput<I> {
    fn to_input(&self) -> I;
}

/// Projects a trainset row into a signature's output type — the gold label.
///
/// Used for seeding labeled few-shot demos from a trainset
/// (`Demo::new(row.to_input(), row.to_output())`). Optimizers that harvest
/// demos from traces don't need it.
pub trait ToOutput<O> {
    fn to_output(&self) -> O;
}

/// Every type trivially projects to itself: an input-only trainset is `Vec<S::Input>`.
impl<T: Clone> ToInput<T> for T {
    fn to_input(&self) -> T {
        self.clone()
    }
}

/// `(input, output)` pairs are rows with no extra fields.
impl<I: Clone, O> ToInput<I> for (I, O) {
    fn to_input(&self) -> I {
        self.0.clone()
    }
}

/// `(input, output)` pairs are rows with no extra fields.
impl<I, O: Clone> ToOutput<O> for (I, O) {
    fn to_output(&self) -> O {
        self.1.clone()
    }
}
