FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

RUN apt-get update
RUN apt update

# Get Ubuntu packages
RUN apt-get install -y \
    build-essential \
    curl \
    wget

# install uv and python
RUN curl -LsSf https://astral.sh/uv/0.6.17/install.sh | sh
RUN ~/.local/bin/uv python install 3.13

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

ENV DO_NOT_TRACK=1
