#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";

const allPackages = [
  "dsrs-core",
  "dsrs-cache",
  "dsrs-trace",
  "dsrs-lm",
  "dsrs-predict",
  "dsrs-evaluate",
  "dsrs-gepa",
  "dsrs-data",
  "dsrs-leaven",
];

const outDir = "target/llvm-cov";
const packageArgs = process.argv
  .map((arg, index, args) => (arg === "--package" || arg === "-p" ? args[index + 1] : null))
  .filter(Boolean);
const packages = packageArgs.length > 0 ? packageArgs : allPackages;
const runBranch = process.argv.includes("--branch") || process.argv.includes("--strict-branch");
const strictBranch = process.argv.includes("--strict-branch");
mkdirSync(outDir, { recursive: true });

function run(args) {
  const result = spawnSync("cargo", args, { stdio: "inherit" });
  return result.status ?? 1;
}

function coveragePercent(summary, key) {
  const totals = summary.data[0].totals[key];
  return {
    covered: totals.covered,
    count: totals.count,
    percent: totals.percent.toFixed(2),
  };
}

function readSummary(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function formatMetric(metric) {
  return `${metric.covered}/${metric.count} (${metric.percent}%)`;
}

const lines = [
  "# Runtime Coverage Summary",
  "",
  "Generated by `tools/coverage-runtime.mjs`.",
  "",
  "## Line Coverage",
  "",
  "| Package | Lines | Functions | Regions |",
  "|---|---:|---:|---:|",
];

let failed = false;

run(["llvm-cov", "clean", "--workspace"]);

for (const pkg of packages) {
  const outputPath = `${outDir}/${pkg}-line-summary.json`;
  const status = run([
    "llvm-cov",
    "-p",
    pkg,
    "--json",
    "--summary-only",
    "--output-path",
    outputPath,
  ]);

  if (status !== 0) {
    failed = true;
    lines.push(`| \`${pkg}\` | FAILED | FAILED | FAILED |`);
    continue;
  }

  const summary = readSummary(outputPath);
  lines.push(
    `| \`${pkg}\` | ${formatMetric(coveragePercent(summary, "lines"))} | ${formatMetric(
      coveragePercent(summary, "functions"),
    )} | ${formatMetric(coveragePercent(summary, "regions"))} |`,
  );
}

lines.push("", "## Branch Coverage", "");

if (!runBranch) {
  lines.push(
    "Not run in this invocation. Pass `--branch` to record branch summaries, or `--strict-branch` to fail on any branch-report failure.",
  );
  writeFileSync(`${outDir}/runtime-coverage-summary.md`, `${lines.join("\n")}\n`);
  console.log(`Wrote ${outDir}/runtime-coverage-summary.md`);
  process.exit(failed ? 1 : 0);
}

lines.push(
  "Branch coverage is attempted package-by-package. The current llvm-cov reporter can segfault on some crates; failures are recorded here instead of being hidden. Pass `--strict-branch` to make any branch-report failure fail this script.",
  "",
  "| Package | Branches | Status |",
  "|---|---:|---|",
);

let branchFailed = false;

run(["llvm-cov", "clean", "--workspace"]);

for (const pkg of packages) {
  const outputPath = `${outDir}/${pkg}-branch-summary.json`;
  const status = run([
    "llvm-cov",
    "-p",
    pkg,
    "--json",
    "--summary-only",
    "--branch",
    "--output-path",
    outputPath,
  ]);

  if (status !== 0) {
    branchFailed = true;
    lines.push(`| \`${pkg}\` | n/a | reporter failed with status ${status} |`);
    continue;
  }

  const summary = readSummary(outputPath);
  lines.push(`| \`${pkg}\` | ${formatMetric(coveragePercent(summary, "branches"))} | ok |`);
}

writeFileSync(`${outDir}/runtime-coverage-summary.md`, `${lines.join("\n")}\n`);
console.log(`Wrote ${outDir}/runtime-coverage-summary.md`);

if (failed || (strictBranch && branchFailed)) {
  process.exit(1);
}
