use anyhow::{Result, anyhow};
use bon::Builder;
use rand::{SeedableRng, rngs::StdRng, seq::SliceRandom};
use tracing::debug;

use crate::evaluate::TypedMetric;
use crate::optimizer::engine::{
    Budget, Candidate, EngineConfig, EvalEngine, EvalOutcome, apply_candidate,
};
use crate::optimizer::harvest::{collect_demo_candidates, select_demos};
use crate::optimizer::{Optimizer, predictor_names, with_named_predictor};
use crate::trace::Trace;
use crate::core::ToInput;
use crate::{Facet, Module, SignatureSchema};

/// The whole-program score recorded on a rollout trace, if a metric ran.
fn trace_score(trace: &Trace) -> Option<f64> {
    trace
        .outcome
        .as_ref()
        .and_then(|outcome| outcome.eval.as_ref())
        .map(|eval| eval.score)
}

/// An instruction candidate with its evaluated score.
///
/// Generated by [`MIPROv2`]'s candidate generation step, then scored by
/// evaluating the module with this instruction on a minibatch.
#[derive(Clone, Debug)]
pub struct PromptCandidate {
    pub instruction: String,
    pub score: f64,
}

impl PromptCandidate {
    pub fn new(instruction: String) -> Self {
        Self {
            instruction,
            score: 0.0,
        }
    }

    pub fn with_score(mut self, score: f64) -> Self {
        self.score = score;
        self
    }
}

/// Library of general prompting best practices used to seed candidate generation.
///
/// These tips are appended to candidate instructions during [`MIPROv2`] optimization
/// to introduce diversity. Each candidate gets a different tip from the rotation.
pub struct PromptingTips {
    pub tips: Vec<String>,
}

impl PromptingTips {
    pub fn default_tips() -> Self {
        Self {
            tips: vec![
                "Use clear and specific language".to_string(),
                "Provide context about the task domain".to_string(),
                "Specify the desired output format".to_string(),
                "Use chain-of-thought reasoning for complex tasks".to_string(),
                "Include few-shot examples when helpful".to_string(),
                "Break down complex instructions into steps".to_string(),
                "Use role-playing (e.g., 'You are an expert...') when appropriate".to_string(),
                "Specify constraints and edge cases".to_string(),
                "Request explanations or reasoning when needed".to_string(),
                "Use structured output formats (JSON, lists, etc.) when applicable".to_string(),
                "Consider the model's strengths and limitations".to_string(),
                "Be explicit about what to avoid or exclude".to_string(),
                "Use positive framing (what to do vs. what not to do)".to_string(),
                "Provide examples of both correct and incorrect outputs when useful".to_string(),
                "Use delimiters or markers to separate different sections".to_string(),
            ],
        }
    }

    pub fn format_for_prompt(&self) -> String {
        self.tips
            .iter()
            .enumerate()
            .map(|(i, tip)| format!("{}. {}", i + 1, tip))
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Trace-guided instruction and demo optimizer.
///
/// MIPROv2 (Multi-prompt Instruction PRoposal Optimizer v2) is a thin strategy
/// over the shared [`EvalEngine`], working in four phases:
///
/// 1. **Trace collection** — one traced teacher pass over the trainset (the
///    engine's baseline candidate), collecting whole-program scores plus
///    per-`Predict` input/output spans
/// 2. **Demo bootstrapping** — successful spans from rollouts scoring at least
///    `min_demo_score` become few-shot demos on the predictor that produced
///    them via the trace name-join (top `max_bootstrapped_demos` by score,
///    deduplicated on inputs), installed through the one candidate seam
/// 3. **Candidate generation** — uses the traces and prompting tips to generate
///    `num_candidates` instruction variants per predictor
/// 4. **Trial evaluation** — evaluates up to `num_trials` candidates on a sampled
///    minibatch through the engine (cached, budget-metered fan-out), keeps the best
///
/// Unlike [`GEPA`](crate::GEPA), MIPROv2 does not require feedback — only numerical scores.
/// Unlike [`COPRO`](crate::COPRO), it uses execution traces to inform candidate generation
/// rather than blind search.
///
/// # Hyperparameters
///
/// - **`num_candidates`** (default: 10) — instruction variants generated per predictor.
/// - **`num_trials`** (default: 20) — maximum candidates evaluated per predictor.
///   If `num_trials` < `num_candidates`, only the first `num_trials` are evaluated.
/// - **`minibatch_size`** (default: 25) — examples per candidate evaluation.
/// - **`max_bootstrapped_demos`** (default: 4) — demos installed per predictor.
/// - **`min_demo_score`** (default: 0.0) — score gate for demo-eligible traces.
/// - **`eval_concurrency`** (default: 16) — LM calls in flight during evaluation.
/// - **`seed`** — fixes minibatch sampling for reproducible runs.
///
/// # Errors
///
/// Any LM-call or metric failure during the teacher pass or a trial evaluation
/// propagates and aborts the run (the engine's evaluation contract).
///
/// # Cost
///
/// Roughly `num_predictors × (trainset_size + num_trials × minibatch_size)` LM calls,
/// minus whatever the engine's rollout cache serves for free (duplicate candidates
/// deduplicate by content hash and re-seen examples cost nothing).
///
/// ```ignore
/// let mipro = MIPROv2::builder()
///     .num_candidates(10)
///     .num_trials(20)
///     .build();
/// mipro.compile(&mut module, trainset, &metric).await?;
/// ```
#[derive(Builder)]
pub struct MIPROv2 {
    /// Instruction variants generated per predictor.
    #[builder(default = 10)]
    pub num_candidates: usize,

    /// Maximum candidates evaluated per predictor.
    #[builder(default = 20)]
    pub num_trials: usize,

    /// Examples per candidate evaluation.
    #[builder(default = 25)]
    pub minibatch_size: usize,

    /// Maximum demos bootstrapped per predictor from successful traces.
    #[builder(default = 4)]
    pub max_bootstrapped_demos: usize,

    /// Minimum whole-program score a trace needs for its per-predictor
    /// input/output pairs to qualify as bootstrapped demos.
    #[builder(default = 0.0)]
    pub min_demo_score: f64,

    /// Concurrent LM calls in flight during candidate evaluation.
    #[builder(default = crate::evaluate::DEFAULT_EVAL_CONCURRENCY)]
    pub eval_concurrency: usize,

    /// Seed for minibatch sampling. `None` uses a nondeterministic seed.
    pub seed: Option<u64>,
}

impl MIPROv2 {
    /// Rollout traces with the highest recorded scores, descending. Traces
    /// without a recorded eval are ignored.
    pub fn select_best_traces<'a>(&self, traces: &'a [Trace], num_select: usize) -> Vec<&'a Trace> {
        let mut scored_traces: Vec<_> = traces
            .iter()
            .filter_map(|t| trace_score(t).map(|score| (score, t)))
            .collect();

        scored_traces.sort_by(|(left, _), (right, _)| {
            right.partial_cmp(left).unwrap_or(std::cmp::Ordering::Equal)
        });

        scored_traces
            .into_iter()
            .take(num_select)
            .map(|(_, t)| t)
            .collect()
    }

    fn generate_candidate_instructions(
        &self,
        program_description: &str,
        traces: &[Trace],
        num_candidates: usize,
    ) -> Vec<String> {
        let tips = PromptingTips::default_tips();
        let score_hint = traces.iter().filter_map(trace_score).fold(0.0f64, f64::max);

        (0..num_candidates)
            .map(|idx| {
                let tip = &tips.tips[idx % tips.tips.len()];
                format!(
                    "{program_description}\n\nOptimization candidate {}:\n- {}\n- Target score >= {:.3}",
                    idx + 1,
                    tip,
                    score_hint
                )
            })
            .collect()
    }

    pub fn create_prompt_candidates(&self, instructions: Vec<String>) -> Vec<PromptCandidate> {
        instructions.into_iter().map(PromptCandidate::new).collect()
    }

    pub fn format_schema_fields(&self, signature: &SignatureSchema) -> String {
        let mut result = String::new();

        result.push_str("Input Fields:\n");
        for field in signature.input_fields() {
            let desc = if field.docs.is_empty() {
                "No description"
            } else {
                field.docs.as_str()
            };
            result.push_str(&format!("  - {}: {}\n", field.lm_name, desc));
        }

        result.push_str("\nOutput Fields:\n");
        for field in signature.output_fields() {
            let desc = if field.docs.is_empty() {
                "No description"
            } else {
                field.docs.as_str()
            };
            result.push_str(&format!("  - {}: {}\n", field.lm_name, desc));
        }

        result
    }
}

impl Optimizer for MIPROv2 {
    type Report = ();

    async fn compile<E, M, MT>(
        &self,
        module: &mut M,
        trainset: Vec<E>,
        metric: &MT,
    ) -> Result<Self::Report>
    where
        E: ToInput<M::Input> + serde::Serialize + Send + Sync,
        M: Module + for<'a> Facet<'a>,
        MT: TypedMetric<E, M>,
    {
        let predictor_names = predictor_names(module)?;

        if predictor_names.is_empty() {
            return Err(anyhow!("no optimizable predictors found"));
        }

        let mut rng = match self.seed {
            Some(seed) => StdRng::seed_from_u64(seed),
            None => StdRng::from_entropy(),
        };

        let mut engine = EvalEngine::new(
            trainset,
            metric,
            EngineConfig {
                concurrency: self.eval_concurrency,
                budget: Budget::unlimited(),
                cache_salt: 0,
            },
        );

        // Phase 1: one traced teacher pass over the trainset — the engine's
        // baseline candidate. Whole-program traces feed candidate generation;
        // per-predictor spans feed demo bootstrapping via the trace name-join
        // (spans record the dotted paths assigned by the naming pass above).
        let baseline = engine.register(Candidate::new());
        let baseline_eval = match engine.evaluate(module, baseline, None).await? {
            EvalOutcome::Complete(eval) => eval,
            EvalOutcome::BudgetExhausted { needed } => {
                return Err(anyhow!(
                    "unexpected budget exhaustion ({needed} rollouts) with an unlimited budget"
                ));
            }
        };
        let scored_traces: Vec<(f64, &Trace)> = baseline_eval
            .rollouts
            .iter()
            .filter_map(|rollout| {
                rollout
                    .trace
                    .as_ref()
                    .map(|trace| (rollout.eval.score, trace))
            })
            .collect();

        // Phase 2: bootstrap demos from successful spans of well-scored
        // rollouts and install them permanently before instruction search, so
        // candidates are scored against the module as it will actually run.
        let bootstrapped_demos = select_demos(
            collect_demo_candidates(scored_traces, self.min_demo_score),
            self.max_bootstrapped_demos,
        );
        if !bootstrapped_demos.is_empty() {
            let mut demo_candidate = Candidate::new();
            for (predictor_name, demos) in bootstrapped_demos {
                debug!(
                    predictor = %predictor_name,
                    demo_count = demos.len(),
                    "installing bootstrapped demos"
                );
                demo_candidate.set_demos(predictor_name, demos);
            }
            let _undo = apply_candidate(module, &demo_candidate)?;
        }

        let traces: Vec<Trace> = baseline_eval
            .rollouts
            .into_iter()
            .filter_map(|rollout| rollout.trace)
            .collect();

        // Phase 3: per-predictor instruction search on a sampled minibatch —
        // one minibatch per predictor round so all candidates score on the
        // same examples and remain comparable.
        let all_indices: Vec<usize> = (0..engine.num_examples()).collect();
        for predictor_name in predictor_names {
            let signature_desc = {
                with_named_predictor(module, &predictor_name, |predictor| {
                    Ok(self.format_schema_fields(predictor.schema()))
                })?
            };

            let instructions =
                self.generate_candidate_instructions(&signature_desc, &traces, self.num_candidates);

            let minibatch_size = all_indices.len().min(self.minibatch_size.max(1));
            let minibatch: Vec<usize> = all_indices
                .choose_multiple(&mut rng, minibatch_size)
                .copied()
                .collect();

            let mut best: Option<(f64, String)> = None;
            for instruction in instructions.into_iter().take(self.num_trials.max(1)) {
                let row =
                    engine.register(Candidate::with_instruction(&predictor_name, &instruction));
                let eval = match engine.evaluate(module, row, Some(&minibatch)).await? {
                    EvalOutcome::Complete(eval) => eval,
                    EvalOutcome::BudgetExhausted { needed } => {
                        return Err(anyhow!(
                            "unexpected budget exhaustion ({needed} rollouts) with an unlimited budget"
                        ));
                    }
                };
                let score = eval.mean();
                if best.as_ref().is_none_or(|(top, _)| score > *top) {
                    best = Some((score, instruction));
                }
            }

            let (_, best_instruction) =
                best.ok_or_else(|| anyhow!("no candidates to evaluate"))?;
            let _undo = apply_candidate(
                module,
                &Candidate::with_instruction(&predictor_name, best_instruction),
            )?;
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use anyhow::{Result, anyhow};

    use super::*;
    use crate::evaluate::{Eval, TypedMetric};
    use crate::{CallMetadata, Predict, PredictError, Predicted, Signature};

    #[derive(Signature, Clone, Debug)]
    struct MiproStateSig {
        #[input]
        prompt: String,

        #[output]
        answer: String,
    }

    #[derive(facet::Facet)]
    #[facet(crate = facet)]
    struct MiproStateModule {
        predictor: Predict<MiproStateSig>,
    }

    impl Module for MiproStateModule {
        type Input = MiproStateSigInput;
        type Output = MiproStateSigOutput;

        async fn forward(
            &self,
            input: MiproStateSigInput,
        ) -> Result<Predicted<MiproStateSigOutput>, PredictError> {
            Ok(Predicted::new(
                MiproStateSigOutput {
                    answer: input.prompt,
                },
                CallMetadata::default(),
            ))
        }
    }

    struct AlwaysFailMetric;

    type MiproRow = (MiproStateSigInput, MiproStateSigOutput);

    impl TypedMetric<MiproRow, MiproStateModule> for AlwaysFailMetric {
        async fn evaluate(
            &self,
            _example: &MiproRow,
            _prediction: &Predicted<MiproStateSigOutput>,
            _trace: Option<&Trace>,
        ) -> Result<Eval> {
            Err(anyhow!("metric failure"))
        }
    }

    fn trainset() -> Vec<MiproRow> {
        vec![(
            MiproStateSigInput {
                prompt: "one".to_string(),
            },
            MiproStateSigOutput {
                answer: "one".to_string(),
            },
        )]
    }

    #[tokio::test]
    async fn compile_restores_state_when_metric_errors() {
        let optimizer = MIPROv2::builder()
            .num_candidates(2)
            .num_trials(1)
            .minibatch_size(1)
            .build();
        let mut module = MiproStateModule {
            predictor: Predict::<MiproStateSig>::builder()
                .instruction("seed-instruction")
                .build(),
        };

        let err = optimizer
            .compile(&mut module, trainset(), &AlwaysFailMetric)
            .await
            .expect_err("candidate evaluation should propagate metric failure");
        assert!(err.to_string().contains("metric failure"));

        let instruction = with_named_predictor(&mut module, "predictor", |predictor| {
            Ok(predictor.instruction())
        })
        .expect("predictor lookup should succeed");
        assert_eq!(instruction, "seed-instruction");
    }
}
