use std::collections::{HashMap, HashSet};

use anyhow::{Result, anyhow};
use bon::Builder;
use rand::{SeedableRng, rngs::StdRng, seq::SliceRandom};
use serde_json::Value;
use tracing::{debug, warn};

use crate::core::StateUpdate;
use crate::evaluate::{TypedMetric, average_score};
use crate::optimizer::{
    Optimizer, evaluate_with_instruction, predictor_names, with_named_predictor,
};
use crate::predictors::Example;
use crate::trace::{JsonMap, Trace, TraceOutcome, capture};
use crate::{Facet, Module, RawExample, Signature, SignatureSchema};

/// The whole-program score recorded on a rollout trace, if a metric ran.
fn trace_score(trace: &Trace) -> Option<f64> {
    trace
        .outcome
        .as_ref()
        .and_then(|outcome| outcome.eval.as_ref())
        .map(|eval| eval.score)
}

/// Builds a demo row from a span's recorded input/output field maps.
fn demo_from_json(input: &JsonMap, output: &JsonMap) -> RawExample {
    let mut data: HashMap<String, Value> = HashMap::with_capacity(input.len() + output.len());
    data.extend(input.iter().map(|(k, v)| (k.clone(), v.clone())));
    data.extend(output.iter().map(|(k, v)| (k.clone(), v.clone())));
    RawExample::new(
        data,
        input.keys().cloned().collect(),
        output.keys().cloned().collect(),
    )
}

fn json_object(value: Result<Value, serde_json::Error>) -> Option<JsonMap> {
    match value {
        Ok(Value::Object(map)) => Some(map),
        _ => None,
    }
}

/// An instruction candidate with its evaluated score.
///
/// Generated by [`MIPROv2`]'s candidate generation step, then scored by
/// evaluating the module with this instruction on a minibatch.
#[derive(Clone, Debug)]
pub struct PromptCandidate {
    pub instruction: String,
    pub score: f64,
}

impl PromptCandidate {
    pub fn new(instruction: String) -> Self {
        Self {
            instruction,
            score: 0.0,
        }
    }

    pub fn with_score(mut self, score: f64) -> Self {
        self.score = score;
        self
    }
}

/// Library of general prompting best practices used to seed candidate generation.
///
/// These tips are appended to candidate instructions during [`MIPROv2`] optimization
/// to introduce diversity. Each candidate gets a different tip from the rotation.
pub struct PromptingTips {
    pub tips: Vec<String>,
}

impl PromptingTips {
    pub fn default_tips() -> Self {
        Self {
            tips: vec![
                "Use clear and specific language".to_string(),
                "Provide context about the task domain".to_string(),
                "Specify the desired output format".to_string(),
                "Use chain-of-thought reasoning for complex tasks".to_string(),
                "Include few-shot examples when helpful".to_string(),
                "Break down complex instructions into steps".to_string(),
                "Use role-playing (e.g., 'You are an expert...') when appropriate".to_string(),
                "Specify constraints and edge cases".to_string(),
                "Request explanations or reasoning when needed".to_string(),
                "Use structured output formats (JSON, lists, etc.) when applicable".to_string(),
                "Consider the model's strengths and limitations".to_string(),
                "Be explicit about what to avoid or exclude".to_string(),
                "Use positive framing (what to do vs. what not to do)".to_string(),
                "Provide examples of both correct and incorrect outputs when useful".to_string(),
                "Use delimiters or markers to separate different sections".to_string(),
            ],
        }
    }

    pub fn format_for_prompt(&self) -> String {
        self.tips
            .iter()
            .enumerate()
            .map(|(i, tip)| format!("{}. {}", i + 1, tip))
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Trace-guided instruction and demo optimizer.
///
/// MIPROv2 (Multi-prompt Instruction PRoposal Optimizer v2) works in four phases:
///
/// 1. **Trace collection** — runs the module on the trainset once under a
///    [`capture()`](crate::trace::capture) scope, collecting whole-program scores
///    plus per-`Predict` input/output spans
/// 2. **Demo bootstrapping** — span input/output pairs from runs scoring at least
///    `min_demo_score` become few-shot demos on the predictor that produced them
///    (top `max_bootstrapped_demos` by score, deduplicated on inputs)
/// 3. **Candidate generation** — uses the traces and prompting tips to generate
///    `num_candidates` instruction variants per predictor
/// 4. **Trial evaluation** — evaluates up to `num_trials` candidates on a sampled
///    minibatch, keeps the best
///
/// Unlike [`GEPA`](crate::GEPA), MIPROv2 does not require feedback — only numerical scores.
/// Unlike [`COPRO`](crate::COPRO), it uses execution traces to inform candidate generation
/// rather than blind search.
///
/// # Hyperparameters
///
/// - **`num_candidates`** (default: 10) — instruction variants generated per predictor.
/// - **`num_trials`** (default: 20) — maximum candidates evaluated per predictor.
///   If `num_trials` < `num_candidates`, only the first `num_trials` are evaluated.
/// - **`minibatch_size`** (default: 25) — examples per candidate evaluation.
/// - **`max_bootstrapped_demos`** (default: 4) — demos installed per predictor.
/// - **`min_demo_score`** (default: 0.0) — score gate for demo-eligible traces.
/// - **`eval_concurrency`** (default: 16) — LM calls in flight during evaluation.
/// - **`seed`** — fixes minibatch sampling for reproducible runs.
///
/// # Cost
///
/// Roughly `num_predictors × (trainset_size + num_trials × minibatch_size)` LM calls.
///
/// ```ignore
/// let mipro = MIPROv2::builder()
///     .num_candidates(10)
///     .num_trials(20)
///     .build();
/// mipro.compile(&mut module, trainset, &metric).await?;
/// ```
#[derive(Builder)]
pub struct MIPROv2 {
    /// Instruction variants generated per predictor.
    #[builder(default = 10)]
    pub num_candidates: usize,

    /// Maximum candidates evaluated per predictor.
    #[builder(default = 20)]
    pub num_trials: usize,

    /// Examples per candidate evaluation.
    #[builder(default = 25)]
    pub minibatch_size: usize,

    /// Maximum demos bootstrapped per predictor from successful traces.
    #[builder(default = 4)]
    pub max_bootstrapped_demos: usize,

    /// Minimum whole-program score a trace needs for its per-predictor
    /// input/output pairs to qualify as bootstrapped demos.
    #[builder(default = 0.0)]
    pub min_demo_score: f64,

    /// Concurrent LM calls in flight during candidate evaluation.
    #[builder(default = crate::evaluate::DEFAULT_EVAL_CONCURRENCY)]
    pub eval_concurrency: usize,

    /// Seed for minibatch sampling. `None` uses a nondeterministic seed.
    pub seed: Option<u64>,
}

impl MIPROv2 {
    /// Runs the module over the trainset once, collecting whole-program rollout
    /// traces *and* per-predictor demo candidates from the recorded spans.
    ///
    /// Each example runs inside a [`capture()`](crate::trace::capture) scope, so
    /// every `Predict` leaf records its own input/output span under the same
    /// dotted-path name the mutation seam addresses (assigned by the optimizer's
    /// naming pass). Successful spans from examples whose final score reaches
    /// `min_demo_score` become demo candidates for the predictor that produced
    /// them — a pure name join, no pointer identity.
    ///
    /// Failing examples (LM error or metric error) are skipped with a warning
    /// instead of aborting the run — a trace pass over an unoptimized module is
    /// expected to have failures; those examples simply contribute no trace.
    async fn generate_traces_with_bootstrap<S, M, MT>(
        &self,
        module: &M,
        examples: &[Example<S>],
        metric: &MT,
    ) -> Result<(Vec<Trace>, HashMap<String, Vec<RawExample>>)>
    where
        S: Signature,
        S::Input: Clone,
        M: Module<Input = S::Input>,
        MT: TypedMetric<S, M>,
    {
        let mut traces = Vec::with_capacity(examples.len());
        let mut demo_candidates: HashMap<String, Vec<(f64, RawExample)>> = HashMap::new();
        let mut skipped = 0usize;

        for example in examples {
            let input = example.input.clone();
            let started = std::time::Instant::now();
            // Metric evaluation happens outside the capture scope so LM-as-judge
            // metrics don't pollute the execution trace with their own spans.
            let (result, mut trace) = capture(|| module.call(input)).await;
            let predicted = match result {
                Ok(predicted) => predicted,
                Err(err) => {
                    debug!(error = %err, "skipping trainset example that failed during trace collection");
                    skipped += 1;
                    continue;
                }
            };
            let eval = match metric.evaluate(example, &predicted, Some(&trace)).await {
                Ok(eval) => eval,
                Err(err) => {
                    debug!(error = %err, "skipping trainset example whose metric evaluation failed");
                    skipped += 1;
                    continue;
                }
            };
            let score = eval.score;
            let (output, _) = predicted.into_parts();
            trace.meta.input = json_object(serde_json::to_value(&example.input));
            trace.outcome = Some(TraceOutcome {
                output: json_object(serde_json::to_value(&output)),
                error: None,
                eval: Some(eval),
                duration_us: started.elapsed().as_micros() as u64,
            });

            if score >= self.min_demo_score {
                for span in trace.successes() {
                    let name = trace.component_name(span.component);
                    if let (Some(span_input), Some(span_output)) = (&span.input, &span.output) {
                        demo_candidates
                            .entry(name.to_string())
                            .or_default()
                            .push((score, demo_from_json(span_input, span_output)));
                    }
                }
            }
            traces.push(trace);
        }

        if skipped > 0 {
            warn!(
                skipped,
                total = examples.len(),
                "some trainset examples failed during trace collection"
            );
        }

        Ok((traces, self.select_demos(demo_candidates)))
    }

    /// Keeps the top `max_bootstrapped_demos` demos per predictor by score,
    /// deduplicated on input fields so repeated inputs don't crowd the demo set.
    fn select_demos(
        &self,
        candidates: HashMap<String, Vec<(f64, RawExample)>>,
    ) -> HashMap<String, Vec<RawExample>> {
        let mut selected = HashMap::with_capacity(candidates.len());
        for (path, mut scored) in candidates {
            scored.sort_by(|(left, _), (right, _)| {
                right.partial_cmp(left).unwrap_or(std::cmp::Ordering::Equal)
            });

            let mut seen_inputs = HashSet::new();
            let mut demos = Vec::new();
            for (_, demo) in scored {
                let mut input_pairs: Vec<(&String, &Value)> = demo
                    .input_keys
                    .iter()
                    .filter_map(|key| demo.data.get(key).map(|value| (key, value)))
                    .collect();
                input_pairs.sort_by_key(|(name, _)| *name);
                let fingerprint = serde_json::to_string(&input_pairs).unwrap_or_default();
                if seen_inputs.insert(fingerprint) {
                    demos.push(demo);
                    if demos.len() >= self.max_bootstrapped_demos {
                        break;
                    }
                }
            }
            if !demos.is_empty() {
                selected.insert(path, demos);
            }
        }
        selected
    }

    /// Rollout traces with the highest recorded scores, descending. Traces
    /// without a recorded eval are ignored.
    pub fn select_best_traces<'a>(&self, traces: &'a [Trace], num_select: usize) -> Vec<&'a Trace> {
        let mut scored_traces: Vec<_> = traces
            .iter()
            .filter_map(|t| trace_score(t).map(|score| (score, t)))
            .collect();

        scored_traces.sort_by(|(left, _), (right, _)| {
            right.partial_cmp(left).unwrap_or(std::cmp::Ordering::Equal)
        });

        scored_traces
            .into_iter()
            .take(num_select)
            .map(|(_, t)| t)
            .collect()
    }

    fn generate_candidate_instructions(
        &self,
        program_description: &str,
        traces: &[Trace],
        num_candidates: usize,
    ) -> Vec<String> {
        let tips = PromptingTips::default_tips();
        let score_hint = traces.iter().filter_map(trace_score).fold(0.0f64, f64::max);

        (0..num_candidates)
            .map(|idx| {
                let tip = &tips.tips[idx % tips.tips.len()];
                format!(
                    "{program_description}\n\nOptimization candidate {}:\n- {}\n- Target score >= {:.3}",
                    idx + 1,
                    tip,
                    score_hint
                )
            })
            .collect()
    }

    pub fn create_prompt_candidates(&self, instructions: Vec<String>) -> Vec<PromptCandidate> {
        instructions.into_iter().map(PromptCandidate::new).collect()
    }

    async fn evaluate_candidate<'a, S, M, MT, I>(
        &self,
        module: &mut M,
        candidate: &PromptCandidate,
        eval_examples: I,
        predictor_name: &str,
        metric: &MT,
    ) -> Result<f64>
    where
        S: Signature,
        S::Input: Clone,
        M: Module<Input = S::Input> + for<'b> Facet<'b>,
        MT: TypedMetric<S, M>,
        I: IntoIterator<Item = &'a Example<S>>,
    {
        let outcomes = evaluate_with_instruction(
            module,
            predictor_name,
            &candidate.instruction,
            eval_examples,
            metric,
            self.eval_concurrency,
        )
        .await?;
        Ok(average_score(&outcomes))
    }

    async fn evaluate_and_select_best<S, M, MT>(
        &self,
        module: &mut M,
        candidates: Vec<PromptCandidate>,
        minibatch: &[&Example<S>],
        predictor_name: &str,
        metric: &MT,
    ) -> Result<PromptCandidate>
    where
        S: Signature,
        S::Input: Clone,
        M: Module<Input = S::Input> + for<'a> Facet<'a>,
        MT: TypedMetric<S, M>,
    {
        let mut evaluated = Vec::new();

        let num_trials = self.num_trials.max(1);
        for candidate in candidates.into_iter().take(num_trials) {
            let score = self
                .evaluate_candidate::<S, _, _, _>(
                    module,
                    &candidate,
                    minibatch.iter().copied(),
                    predictor_name,
                    metric,
                )
                .await?;
            evaluated.push(candidate.with_score(score));
        }

        evaluated
            .into_iter()
            .max_by(|a, b| {
                a.score
                    .partial_cmp(&b.score)
                    .unwrap_or(std::cmp::Ordering::Equal)
            })
            .ok_or_else(|| anyhow!("no candidates to evaluate"))
    }

    pub fn format_schema_fields(&self, signature: &SignatureSchema) -> String {
        let mut result = String::new();

        result.push_str("Input Fields:\n");
        for field in signature.input_fields() {
            let desc = if field.docs.is_empty() {
                "No description"
            } else {
                field.docs.as_str()
            };
            result.push_str(&format!("  - {}: {}\n", field.lm_name, desc));
        }

        result.push_str("\nOutput Fields:\n");
        for field in signature.output_fields() {
            let desc = if field.docs.is_empty() {
                "No description"
            } else {
                field.docs.as_str()
            };
            result.push_str(&format!("  - {}: {}\n", field.lm_name, desc));
        }

        result
    }
}

impl Optimizer for MIPROv2 {
    type Report = ();

    async fn compile<S, M, MT>(
        &self,
        module: &mut M,
        trainset: Vec<Example<S>>,
        metric: &MT,
    ) -> Result<Self::Report>
    where
        S: Signature,
        S::Input: Clone,
        M: Module<Input = S::Input> + for<'a> Facet<'a>,
        MT: TypedMetric<S, M>,
    {
        let predictor_names = predictor_names(module)?;

        if predictor_names.is_empty() {
            return Err(anyhow!("no optimizable predictors found"));
        }

        let mut rng = match self.seed {
            Some(seed) => StdRng::seed_from_u64(seed),
            None => StdRng::from_entropy(),
        };

        // Phase 1: one traced pass over the trainset. Whole-program traces feed
        // candidate generation; per-predictor input/output spans from successful
        // runs become bootstrapped demos (joined by the names assigned in the
        // predictor_names naming pass above).
        let (traces, bootstrapped_demos) = self
            .generate_traces_with_bootstrap::<S, _, _>(module, &trainset, metric)
            .await?;

        // Phase 2: install demos before instruction search so candidates are
        // scored against the module as it will actually run.
        for (predictor_name, demos) in &bootstrapped_demos {
            debug!(
                predictor = %predictor_name,
                demo_count = demos.len(),
                "installing bootstrapped demos"
            );
            with_named_predictor(module, predictor_name, |predictor| {
                predictor.apply_update(StateUpdate::demos(demos.clone()))
            })?;
        }

        // Phase 3: per-predictor instruction search on a sampled minibatch —
        // one minibatch per predictor round so all candidates score on the
        // same examples and remain comparable.
        for predictor_name in predictor_names {
            let signature_desc = {
                with_named_predictor(module, &predictor_name, |predictor| {
                    Ok(self.format_schema_fields(predictor.schema()))
                })?
            };

            let instructions =
                self.generate_candidate_instructions(&signature_desc, &traces, self.num_candidates);
            let candidates = self.create_prompt_candidates(instructions);

            let minibatch_size = trainset.len().min(self.minibatch_size.max(1));
            let minibatch: Vec<&Example<S>> =
                trainset.choose_multiple(&mut rng, minibatch_size).collect();

            let best_candidate = self
                .evaluate_and_select_best::<S, _, _>(
                    module,
                    candidates,
                    &minibatch,
                    &predictor_name,
                    metric,
                )
                .await?;

            with_named_predictor(module, &predictor_name, |predictor| {
                predictor.apply_update(StateUpdate::instruction(Some(
                    best_candidate.instruction.clone(),
                )))
            })?;
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use anyhow::{Result, anyhow};

    use super::*;
    use crate::evaluate::{Eval, TypedMetric};
    use crate::{CallMetadata, Predict, PredictError, Predicted, Signature};

    #[derive(Signature, Clone, Debug)]
    struct MiproStateSig {
        #[input]
        prompt: String,

        #[output]
        answer: String,
    }

    #[derive(facet::Facet)]
    #[facet(crate = facet)]
    struct MiproStateModule {
        predictor: Predict<MiproStateSig>,
    }

    impl Module for MiproStateModule {
        type Input = MiproStateSigInput;
        type Output = MiproStateSigOutput;

        async fn forward(
            &self,
            input: MiproStateSigInput,
        ) -> Result<Predicted<MiproStateSigOutput>, PredictError> {
            Ok(Predicted::new(
                MiproStateSigOutput {
                    answer: input.prompt,
                },
                CallMetadata::default(),
            ))
        }
    }

    struct AlwaysFailMetric;

    impl TypedMetric<MiproStateSig, MiproStateModule> for AlwaysFailMetric {
        async fn evaluate(
            &self,
            _example: &Example<MiproStateSig>,
            _prediction: &Predicted<MiproStateSigOutput>,
            _trace: Option<&Trace>,
        ) -> Result<Eval> {
            Err(anyhow!("metric failure"))
        }
    }

    fn trainset() -> Vec<Example<MiproStateSig>> {
        vec![Example::new(
            MiproStateSigInput {
                prompt: "one".to_string(),
            },
            MiproStateSigOutput {
                answer: "one".to_string(),
            },
        )]
    }

    #[tokio::test]
    async fn evaluate_candidate_restores_state_when_metric_errors() {
        let optimizer = MIPROv2::builder()
            .num_candidates(2)
            .num_trials(1)
            .minibatch_size(1)
            .build();
        let mut module = MiproStateModule {
            predictor: Predict::<MiproStateSig>::builder()
                .instruction("seed-instruction")
                .build(),
        };
        let candidate = PromptCandidate::new("candidate instruction".to_string());

        let err = optimizer
            .evaluate_candidate::<MiproStateSig, _, _, _>(
                &mut module,
                &candidate,
                &trainset(),
                "predictor",
                &AlwaysFailMetric,
            )
            .await
            .expect_err("candidate evaluation should propagate metric failure");
        assert!(err.to_string().contains("metric failure"));

        let instruction = with_named_predictor(&mut module, "predictor", |predictor| {
            Ok(predictor.instruction())
        })
        .expect("predictor lookup should succeed");
        assert_eq!(instruction, "seed-instruction");
    }
}
